feat: Added the first part of the series on security (supply chain)
karakun/karakun.github.io pull request #237
Opened 2024-04-30 13:24 UTC by ixchelruiz

2024-05-08 06:43 UTC, madmas requested changes
great article, thank you

only chaged the publish date :)

2024-05-08 06:43 UTC, madmas commented on _posts/2024-04-30-security-slsa.md
> +permalink: '/2024/04/30/security-slsa.html'
```suggestion
permalink: '/2024/06/12/security-slsa.html'
```

please also rename the file

2024-05-08 06:43 UTC, madmas commented on _posts/2024-04-30-security-slsa.md
> +![SLSA Supply chain threats](/assets/posts/2024-04-30-security-slsa/2024-04-30-supply-chain-threats.svg)
```suggestion
![SLSA Supply chain threats](/assets/posts/2024-06-12-security-slsa/2024-06-12-supply-chain-threats.svg)
```

please also rename directory and file

2024-05-14 22:43 UTC, grigala commented on _posts/2024-04-30-security-slsa.md
> +Artifacts Integrity is about the ability to trust the authenticity of artifacts, meaning verifying that the artifact you get is really the original artifact uploaded by its author. Establishing the p
```suggestion
Artifacts Integrity is about the ability to trust the authenticity of artifacts, meaning verifying that the artifact you get is really the original artifact uploaded by its author. Establishing the provenance of the artifacts produced is extremely important. So what is _"Provenance"_ all about?
```

2024-05-16 08:30 UTC, ixchelruiz commented on assets/featuredImages/security.png
@grigala Thank You!

2024-05-16 08:35 UTC, grigala approved these changes

2024-06-04 08:49 UTC, merged